[build]
  # Publier depuis le dossier releases/current (lien symlink vers la dernière version)
  publish = "releases/current"

[context.production]
  environment = { GITHUB_TOKEN = "@github-token" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
