name: myportfolio
description: Portfolio de Josoa Vonjiniaina - Full Stack Developer, spécialisé en Flutter, Linux et sécurité.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^8.0.1
  url_launcher: ^6.3.2
  http: ^1.1.0
  fl_chart: ^1.1.1
  font_awesome_flutter: ^10.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
#fonts:
#    - family: TiltNeon
#      fonts:
#       - asset: assets/fonts/TiltNeon-Regular-VariableFont_XROT,YROT.ttf
#    - family: Josefin
#      fonts:
#        - asset: assets/fonts/JosefinSans-VariableFont_wght.ttf
#        - asset: assets/fonts/JosefinSans-Italic-VariableFont_wght.ttf
#    - family: PatrickHand
#      fonts:
#        - assets/asset: fonts/PatrickHandSC-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
     - fonts/

  
  fonts:
    - family: PatrickHand 
      fonts:
      - asset: fonts/PatrickHandSC-Regular.ttf

    - family: Josefin
      fonts:
      - asset: fonts/JosefinSans-VariableFont_wght.ttf
    
    - family: TiltNeon 
      fonts:
      - asset: fonts/TiltNeon-Regular.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with 
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/LogoPrincipalFinal.png"
  image_path_android: "assets/AndroidLogo.svg"
  min_sdk_android: 21
  remove_alpha_ios: true
