#!/bin/bash

# Script de release pour MyPortfolio
# Usage: ./release.sh [version] [message]
# Exemple: ./release.sh 1.0.0 "Initial release"

set -e

# Couleurs pour l'output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
VERSION=${1:-"1.0.0"}
MESSAGE=${2:-"Release version $VERSION"}
RELEASE_DIR="releases"
APK_NAME="myportfolio-v${VERSION}.apk"
APK_SOURCE="build/app/outputs/flutter-apk/app-release.apk"

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║        MyPortfolio Release Script - v${VERSION}                    ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Vérifier que nous sommes dans le bon répertoire
if [ ! -f "pubspec.yaml" ]; then
    echo -e "${RED}❌ Erreur: pubspec.yaml non trouvé. Exécute ce script depuis la racine du projet.${NC}"
    exit 1
fi

# Étape 1: Nettoyer les anciens builds
echo -e "${YELLOW}1️⃣  Nettoyage des builds précédents...${NC}"
flutter clean
echo -e "${GREEN}   ✓ Nettoyage terminé${NC}"
echo ""

# Étape 2: Obtenir les dépendances
echo -e "${YELLOW}2️⃣  Installation des dépendances...${NC}"
flutter pub get
echo -e "${GREEN}   ✓ Dépendances installées${NC}"
echo ""

# Étape 3: Générer l'APK release
echo -e "${YELLOW}3️⃣  Construction de l'APK en mode release...${NC}"
flutter build apk --release --obfuscate --split-debug-info=build/app/outputs/symbols
if [ ! -f "$APK_SOURCE" ]; then
    echo -e "${RED}❌ Erreur: APK non généré ($APK_SOURCE)${NC}"
    exit 1
fi
echo -e "${GREEN}   ✓ APK généré avec succès${NC}"
echo ""

# Étape 4: Créer le dossier releases s'il n'existe pas
echo -e "${YELLOW}4️⃣  Préparation du dossier releases...${NC}"
mkdir -p "$RELEASE_DIR"
echo -e "${GREEN}   ✓ Dossier releases prêt${NC}"
echo ""

# Étape 5: Copier l'APK
echo -e "${YELLOW}5️⃣  Copie de l'APK...${NC}"
cp "$APK_SOURCE" "$RELEASE_DIR/$APK_NAME"
APK_SIZE=$(du -h "$RELEASE_DIR/$APK_NAME" | cut -f1)
echo -e "${GREEN}   ✓ APK copié: $APK_NAME ($APK_SIZE)${NC}"
echo ""

# Étape 6: Créer un fichier info de la release
echo -e "${YELLOW}6️⃣  Création du fichier info...${NC}"
cat > "$RELEASE_DIR/RELEASE-${VERSION}.md" << EOF
# MyPortfolio Release v${VERSION}

**Date:** $(date '+%d/%m/%Y à %H:%M:%S')
**Fichier:** $APK_NAME
**Taille:** $APK_SIZE

## Notes
$MESSAGE

## Installation
1. Télécharge \`$APK_NAME\`
2. Active les sources inconnues dans les paramètres Android
3. Ouvre le fichier APK pour installer

## Spécifications
- **Version:** $VERSION
- **Package:** com.shadowcraft.myportfolio
- **SDK Min:** Android 21 (5.0)
- **Cible:** Android 36 (15.0)

---
Generated by release script
EOF
echo -e "${GREEN}   ✓ Fichier info créé${NC}"
echo ""

# Étape 7: Git - Stage des fichiers
echo -e "${YELLOW}7️⃣  Staging des fichiers...${NC}"
git add "$RELEASE_DIR/$APK_NAME"
git add "$RELEASE_DIR/RELEASE-${VERSION}.md"
echo -e "${GREEN}   ✓ Fichiers stagés${NC}"
echo ""

# Étape 8: Git - Commit
echo -e "${YELLOW}8️⃣  Création du commit...${NC}"
COMMIT_MESSAGE="Release: MyPortfolio v${VERSION}

- Build APK release
- Size: $APK_SIZE
- Message: $MESSAGE"

git commit -m "$COMMIT_MESSAGE"
echo -e "${GREEN}   ✓ Commit créé${NC}"
echo ""

# Étape 9: Créer et pousser le tag
echo -e "${YELLOW}9️⃣  Création du tag Git...${NC}"
git tag -a "v${VERSION}" -m "Release version ${VERSION}"
echo -e "${GREEN}   ✓ Tag créé: v${VERSION}${NC}"
echo ""

# Étape 10: Push
echo -e "${YELLOW}🔟 Push vers le repository...${NC}"
git push origin HEAD
git push origin "v${VERSION}"
echo -e "${GREEN}   ✓ Push réussi${NC}"
echo ""

# Résumé final
echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}✅ Release v${VERSION} terminée avec succès!${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BLUE}📊 Résumé:${NC}"
echo -e "   • Version: ${GREEN}$VERSION${NC}"
echo -e "   • Fichier: ${GREEN}$APK_NAME${NC}"
echo -e "   • Taille: ${GREEN}$APK_SIZE${NC}"
echo -e "   • Tag: ${GREEN}v${VERSION}${NC}"
echo -e "   • Message: ${GREEN}$MESSAGE${NC}"
echo ""
echo -e "${BLUE}📝 Prochaines étapes:${NC}"
echo -e "   1. Va sur GitHub → Releases"
echo -e "   2. Cherche le tag ${GREEN}v${VERSION}${NC}"
echo -e "   3. Clique sur 'Create release from tag'"
echo -e "   4. Le fichier APK est déjà dans ${GREEN}releases/${NC}"
echo ""
